### ISSUE TITLE
"Available on npm" is not accurate in all cases

### ISSUE THREAD

**Issue by MylesBorins** [Checkmarx/cuteboi#4]
Thanks much for putting together this awesome landing page. As an FYI when taking down pacakges that have been on the registry more than 3 days we create a security holding package. As such you are identifying pacakges as still being live with malware when they instead have holding packages

For example https://www.npmjs.com/package/yqsduvkzbpcienfg is still identified as "live", but it has been removed and the publishing user banned.

**Comment by jossef** [comment]
Hi @MylesBorins,

The package's status is being updated via a specific cron-triggered GitHub action. It checks the availability and if something changed upstream the job opens a pull request with an update.

Right after you open this issue there was an automatic PR opened for review - https://github.com/Checkmarx/cuteboi/pull/5
![image](https://user-images.githubusercontent.com/1287098/178431584-4e4c0063-8310-4a2a-8e41-dbb98d91ef00.png)

Thanks for reporting! it is now updated
